version: '3.8'

services:
  db:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=market_db
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_MAX_ALLOWED_PACKET=1G
    command: --max-allowed-packet=200M
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - elk

  market:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/market_db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db
    networks:
      - elk

volumes:
  mysql_data:

networks:
  elk:
